export type Locale = "vi" | "en";

export type ModuleCopy = {
  title: string;
  eyebrow: string;
  overviewTitle: string;
  overview: string;
  overviewContinuation?: string;
  benefits: readonly string[];
  workflowTitle: string;
  workflowIntro: string;
  workflow: readonly string[];
  featuresTitle: string;
  features: readonly { title: string; text: string }[];
  detailTitle: string;
  detail: readonly string[];
  valuesTitle: string;
  values: readonly { title: string; text: string }[];
  experienceTitle: string;
  ctaTitle: string;
  ctaText: string;
  demo: string;
  contact: string;
};

export type ModulePageConfig = {
  slug: string;
  icon: string;
  heroImage: string;
  overviewImages: readonly string[];
  experienceImages?: readonly string[];
  accent: string;
  accentDark: string;
  copy: Record<Locale, ModuleCopy>;
};

export const modulePages = {
  safetyObservation: {
    slug: "safety-observation",
    icon: "/assets/module-solutions/safety-observation.png",
    heroImage: "/assets/risk-management/hero-risk-assessment.png",
    overviewImages: ["/assets/risk-management/hero-risk-assessment.png", "/assets/contractor-management/value-risk-management.png", "/assets/csms/core-workplace.jpg"],
    experienceImages: [
      "/assets/module-solutions/screenshots/safety-observation/category-config.png",
      "/assets/module-solutions/screenshots/safety-observation/create-report.png",
      "/assets/module-solutions/screenshots/safety-observation/employee-reports.png",
      "/assets/module-solutions/screenshots/safety-observation/report-entry.png",
    ],
    accent: "#f59e0b",
    accentDark: "#9a4f05",
    copy: {
      vi: {
        title: "Báo cáo quan sát an toàn",
        eyebrow: "BÁO CÁO QUAN SÁT AN TOÀN",
        overviewTitle: "Chủ động phát hiện trước khi sự cố xảy ra",
        overview: "Quan sát an toàn giúp doanh nghiệp giám sát hành vi làm việc, điều kiện môi trường và quy trình vận hành; từ đó phát hiện sớm hành vi không an toàn, mối nguy và rủi ro tiềm ẩn trước khi gây ra tai nạn hoặc sự cố.",
        benefits: ["Ghi nhận nhanh ngay tại hiện trường", "Theo dõi hành động khắc phục đến khi đóng sự vụ"],
        workflowTitle: "Quy trình quan sát an toàn",
        workflowIntro: "Một luồng khép kín từ ghi nhận mối nguy đến phân tích xu hướng và phòng ngừa tái diễn.",
        workflow: ["Báo cáo mối nguy hoặc rủi ro", "Thông báo, xem xét và phân công khắc phục", "Theo dõi thực hiện và đóng sự vụ", "Phân tích xu hướng và dự báo rủi ro"],
        featuresTitle: "Nhóm tính năng",
        features: [
          { title: "Truy cập tức thì & chọn bộ phận, khu vực", text: "Truy cập bằng đường dẫn trực tiếp hoặc mã QR để xác định chính xác phòng ban và khu vực làm việc." },
          { title: "Ghi nhận nhanh sự việc an toàn", text: "Ghi nhận sự việc an toàn nhanh chóng từ danh mục có sẵn." },
          { title: "Đề xuất hành động khắc phục", text: "Đề xuất ngay hành động khắc phục phù hợp tại hiện trường." },
          { title: "Tự động chuyển báo cáo đến quản lý", text: "Tự động chuyển giao báo cáo đến quản lý trực tiếp để xem xét và xử lý." },
        ],
        detailTitle: "Từ quan sát hiện trường đến dữ liệu phòng ngừa",
        detail: [
          "Dữ liệu quan sát được tập trung thành cơ sở báo cáo mối nguy, giúp doanh nghiệp không chỉ nhận diện hành vi hoặc điều kiện mất an toàn mà còn bảo đảm từng vấn đề được theo dõi đến khi xử lý hoàn tất.",
          "Khi dữ liệu được tích lũy có hệ thống, ban quản lý có thể phân tích xu hướng, nhận biết điểm nóng và chủ động triển khai biện pháp phòng ngừa, góp phần xây dựng văn hóa an toàn và cải tiến liên tục.",
        ],
        valuesTitle: "Giá trị mang lại",
        values: [
          { title: "Chủ động phòng ngừa", text: "Phát hiện mối nguy trước khi phát sinh sự cố." },
          { title: "Cải tiến liên tục", text: "Biến từng quan sát thành hành động cải thiện có thể theo dõi." },
          { title: "Nâng cao nhận thức về an toàn", text: "Khuyến khích mọi nhân sự cùng tham gia xây dựng an toàn." },
          { title: "Minh bạch và hiệu quả", text: "Theo dõi trách nhiệm, tiến độ và kết quả trên một hệ thống." },
        ],
        experienceTitle: "TRẢI NGHIỆM NGƯỜI DÙNG",
        ctaTitle: "Biến mỗi quan sát thành một hành động an toàn",
        ctaText: "Chuẩn hóa hoạt động báo cáo, xử lý và phân tích mối nguy trên toàn doanh nghiệp.",
        demo: "Đăng ký demo",
        contact: "Liên hệ tư vấn",
      },
      en: {
        title: "Behavior-Based Safety",
        eyebrow: "BEHAVIOR-BASED SAFETY",
        overviewTitle: "Detect issues before incidents happen",
        overview: "Safety observation helps organizations monitor work behavior, environmental conditions and operating procedures so unsafe acts and potential hazards can be identified before they cause an accident or incident.",
        benefits: ["Fast reporting from the field", "Corrective actions tracked through closure"],
        workflowTitle: "Safety observation workflow",
        workflowIntro: "A closed loop from hazard reporting to trend analysis and prevention.",
        workflow: ["Hazard or risk reporting", "Notification, review and corrective assignment", "Action follow-up and closure", "Predictive trend analysis"],
        featuresTitle: "Core features",
        features: [
          { title: "Instant access & location tagging", text: "Use a direct link or QR code to identify the exact department and work area." },
          { title: "Smart observation logging", text: "Record safety observations quickly from a prepared list." },
          { title: "Actionable remediation", text: "Propose an appropriate corrective action directly at the worksite." },
          { title: "Automated manager routing", text: "Automatically route the report to the direct manager for review and action." },
        ],
        detailTitle: "From field observations to preventive insight",
        detail: [
          "Observations are centralized in a hazard reporting database so organizations can identify unsafe acts and conditions while tracking every issue through effective resolution.",
          "With structured historical data, management can analyze trends, identify hotspots and act proactively, supporting a stronger safety culture and continuous improvement.",
        ],
        valuesTitle: "Business value",
        values: [
          { title: "Proactive prevention", text: "Identify hazards before they become incidents." },
          { title: "Continuous improvement", text: "Turn observations into trackable improvement actions." },
          { title: "Enhanced safety awareness", text: "Engage the workforce in building everyday safety." },
          { title: "Transparency and efficiency", text: "Track ownership, progress and outcomes in one system." },
        ],
        experienceTitle: "USER EXPERIENCE",
        ctaTitle: "Turn every observation into safer work",
        ctaText: "Standardize hazard reporting, corrective action and trend analysis across your organization.",
        demo: "Book a demo",
        contact: "Contact us",
      },
    },
  },
  equipmentManagement: {
    slug: "equipment-management",
    icon: "/assets/module-solutions/equipment-management.png",
    heroImage: "/assets/module-solutions/equipment-high-risk-inspection.png",
    overviewImages: ["/assets/module-solutions/equipment-high-risk-inspection.png", "/assets/module-solutions/equipment-forklift-inspection.png", "/assets/contractor-management/value-industry-adaptability.png"],
    experienceImages: [
      "/assets/module-solutions/screenshots/equipment-management/add-device.png",
      "/assets/module-solutions/screenshots/equipment-management/report-results.png",
      "/assets/module-solutions/screenshots/equipment-management/inspection-plan.png",
      "/assets/module-solutions/screenshots/equipment-management/device-groups.png",
      "/assets/module-solutions/screenshots/equipment-management/maintenance-plan.png",
    ],
    accent: "#2563eb",
    accentDark: "#153e87",
    copy: {
      vi: {
        title: "Quản lý thiết bị rủi ro cao",
        eyebrow: "EQUIPMENT MANAGEMENT",
        overviewTitle: "Quản lý tập trung vòng đời thiết bị",
        overview: "Giải pháp giúp doanh nghiệp theo dõi, bảo trì và sử dụng hiệu quả thiết bị có yêu cầu nghiêm ngặt về an toàn; qua đó kéo dài tuổi thọ, duy trì hiệu suất và hạn chế thời gian ngừng hoạt động ngoài kế hoạch.",
        benefits: ["Kiểm định và bảo trì đúng hạn", "Hồ sơ thiết bị sẵn sàng truy xuất"],
        workflowTitle: "Quy trình quản lý thiết bị",
        workflowIntro: "Từ danh mục thiết bị đến lịch kiểm định, kết quả và báo cáo trên một luồng dữ liệu thống nhất.",
        workflow: ["Tạo danh mục thiết bị", "Phân quyền người dùng", "Thiết lập lịch kiểm tra, kiểm định", "Thông báo lịch kiểm tra", "Cập nhật kết quả", "Quản lý hồ sơ và biên bản", "Tạo báo cáo, xuất dữ liệu"],
        featuresTitle: "Nhóm tính năng",
        features: [
          { title: "Tập trung hóa & quản lý HRE toàn tổ chức", text: "Tập trung hóa và quản lý thiết bị có yêu cầu nghiêm ngặt về an toàn trong toàn tổ chức." },
          { title: "Lập lịch kiểm định & bảo trì phòng ngừa HRE", text: "Lập lịch kiểm định, bảo trì phòng ngừa và cập nhật kết quả cho thiết bị HRE." },
          { title: "Quản lý chứng nhận & tài liệu kỹ thuật", text: "Quản lý giấy chứng nhận và sách hướng dẫn nhằm đảm bảo tuân thủ pháp luật và tiêu chuẩn ngành." },
          { title: "Phối hợp làm việc & thông báo", text: "Hỗ trợ phối hợp giữa các bộ phận và gửi thông báo để theo dõi đúng thời điểm." },
        ],
        detailTitle: "Quản lý thiết bị",
        detail: [
          "Hệ thống Quản lý thiết bị cung cấp giải pháp toàn diện giúp doanh nghiệp tối ưu hóa các tài sản cốt lõi, cho phép kiểm soát và quản lý tập trung toàn bộ trang thiết bị trên toàn hệ thống tổ chức.",
          "Để tối đa hóa hiệu quả, hệ thống tích hợp các tính năng kiểm định định kỳ, thiết lập lịch bảo trì phòng ngừa và cập nhật kết quả tức thời, đảm bảo máy móc luôn duy trì hiệu suất vận hành tối ưu. Đồng thời, công tác quản lý chứng nhận và tài liệu kỹ thuật cũng được số hóa, đảm bảo tính cập nhật và tuân thủ tuyệt đối các quy định pháp luật và tiêu chuẩn ngành.",
          "Với mục tiêu vận hành không gián đoạn, hệ thống thúc đẩy sự tương tác, phối hợp nhịp nhàng giữa các phòng ban thông qua cơ chế thông báo, giúp đội ngũ nhân sự luôn bám sát tình hình và hành động kịp thời.",
        ],
        valuesTitle: "Giá trị mang lại",
        values: [
          { title: "Tập trung hóa dữ\u00a0liệu", text: "Một hồ sơ số xuyên suốt cho từng thiết bị." },
          { title: "Bảo trì chủ động", text: "Chủ động lịch kiểm tra và hạn chế dừng máy bất ngờ." },
          { title: "Tuân thủ quy định pháp luật", text: "Duy trì chứng nhận và hồ sơ phục vụ kiểm tra." },
          { title: "Phối hợp hiệu quả", text: "Cùng theo dõi thông tin và hành động đúng thời điểm." },
        ],
        experienceTitle: "TỐI ƯU HIỆU SUẤT\nDẪN BƯỚC TƯƠNG LAI",
        ctaTitle: "Chủ động kiểm soát thiết bị quan trọng",
        ctaText: "Số hóa hồ sơ, lịch kiểm định và bảo trì để vận hành an toàn, liên tục.",
        demo: "Đăng ký demo",
        contact: "Liên hệ tư vấn",
      },
      en: {
        title: "High Risk Equipment Management",
        eyebrow: "EQUIPMENT MANAGEMENT",
        overviewTitle: "Centralize the complete equipment lifecycle",
        overview: "Manage, maintain and use high-risk equipment effectively to extend service life, sustain performance and reduce repair cost and unexpected downtime.",
        benefits: ["On-time inspection and maintenance", "Equipment records ready for review"],
        workflowTitle: "Equipment management workflow",
        workflowIntro: "Connect the equipment register, inspection schedules, results and reports in one data flow.",
        workflow: ["Create equipment list", "Manage user permissions", "Configure inspection schedules", "Send inspection notifications", "Update results", "Manage inspection records", "Generate reports and export data"],
        featuresTitle: "Core features",
        features: [
          { title: "Centralize & Manage HREs in organization", text: "Manage high-risk equipment consistently across the organization." },
          { title: "HRE testing & Preventive Maintenance scheduling & Result update", text: "Schedule testing and maintenance and update results promptly." },
          { title: "Manage certificates/manuals to ensure legal and industry compliance", text: "Keep certificates, inspection records and technical manuals linked to each asset." },
          { title: "Collaboration & Notifications", text: "Coordinate teams and automate reminders for important milestones." },
        ],
        detailTitle: "Keep equipment safe and operationally ready",
        detail: [
          "The system centralizes equipment data, inspection history, maintenance activity and supporting records so responsible teams can work from one reliable source.",
          "Scheduling and notification capabilities help departments coordinate on time, reduce missed inspection or maintenance dates and maintain equipment in an appropriate operating state.",
        ],
        valuesTitle: "Business value",
        values: [
          { title: "Data centralization", text: "One digital record across each asset lifecycle." },
          { title: "Proactive maintenance", text: "Plan inspections and reduce unexpected downtime." },
          { title: "Regulatory compliance", text: "Keep certificates and inspection records review-ready." },
          { title: "Effective collaboration", text: "Share updates and act at the right time." },
        ],
        experienceTitle: "OPTIMIZE PERFORMANCE\nLEAD THE FUTURE",
        ctaTitle: "Take control of critical equipment",
        ctaText: "Digitize records, inspections and maintenance for safer, more continuous operations.",
        demo: "Book a demo",
        contact: "Contact us",
      },
    },
  },
  environmentalManagement: {
    slug: "environmental-management",
    icon: "/assets/module-solutions/environmental-management.png",
    heroImage: "/assets/contractor-management/value-industry-adaptability.png",
    overviewImages: ["/assets/contractor-management/value-industry-adaptability.png", "/assets/contractor-management/brand-construction-blue-hour.png", "/assets/csms/core-workplace.jpg"],
    experienceImages: [
      "/assets/module-solutions/screenshots/environmental-management/dashboard.png",
      "/assets/module-solutions/screenshots/environmental-management/monitoring-plans.png",
      "/assets/module-solutions/screenshots/environmental-management/locations.png",
      "/assets/module-solutions/screenshots/environmental-management/result-entry.png",
      "/assets/module-solutions/screenshots/environmental-management/criteria.png",
    ],
    accent: "#16a34a",
    accentDark: "#116334",
    copy: {
      vi: {
        title: "Quan trắc môi trường lao động",
        eyebrow: "QUAN TRẮC MÔI TRƯỜNG LAO ĐỘNG",
        overviewTitle: "Số hóa toàn bộ quy trình quan trắc môi trường lao động",
        overview: "Phần mềm quan trắc môi trường lao động là một giải pháp kỹ thuật số toàn diện, được thiết kế nhằm tối ưu hóa và tự động hóa toàn bộ quy trình giám sát môi trường của doanh nghiệp. Từ việc cấu hình các khu vực giám sát tùy chỉnh, thiết lập các thông số theo quy định pháp luật, đến việc lập lịch lấy mẫu tự động và tập trung hóa dữ liệu nhập từ thực địa, hệ thống thay thế các quy trình thủ công dễ phát sinh sai sót bằng sự chính xác, liền mạch trên nền tảng số.",
        benefits: ["Loại bỏ quy trình nhập liệu phân mảnh", "Dữ liệu minh bạch, sẵn sàng truy xuất"],
        workflowTitle: "Quy trình quan trắc môi trường lao động",
        workflowIntro: "Chuẩn hóa từ cấu hình khu vực, thiết lập tiêu chí đến lập kế hoạch và nhập kết quả quan trắc.",
        workflow: ["Cấu hình khu vực đo kiểm", "Tạo các tiêu chí đo", "Chọn tiêu chí cho từng khu vực", "Tạo kế hoạch quan trắc", "Nhập kết quả quan trắc"],
        featuresTitle: "Nhóm tính năng",
        features: [
          { title: "Đảm bảo tuân thủ & khởi tạo quy trình môi trường", text: "Thiết lập khu vực, thông số và ngưỡng theo nhu cầu quản lý của doanh nghiệp." },
          { title: "Lập kế hoạch quan trắc & nhập kết quả lấy mẫu", text: "Tạo kế hoạch quan trắc, phân công và cập nhật kết quả lấy mẫu đúng tiến độ." },
          { title: "Nhập & quản lý dữ liệu quan trắc tập trung", text: "Nhập, lưu trữ và truy xuất kết quả quan trắc trên một hệ thống." },
          { title: "Theo dõi hiệu suất môi trường & rủi ro", text: "Tổng hợp chỉ số để nhận biết bất thường và chủ động xử lý." },
        ],
        detailTitle: "Quan trắc môi trường lao động",
        detail: [
          "Trong bối cảnh các quy định pháp lý ngày càng chặt chẽ, quản lý tác động môi trường không còn dừng lại ở nghĩa vụ vận hành thông thường—đó là trụ cột cốt lõi đảm bảo sự linh hoạt và phát triển bền vững của doanh nghiệp. Phần mềm quan trắc môi trường lao động chính là cầu nối thu hẹp khoảng cách giữa các thao tác phức tạp ngoài hiện trường và công tác quản trị cấp cao, biến dữ liệu đo kiểm phân mảnh thành một hệ sinh thái tập trung và giàu giá trị ứng dụng.",
          "Bằng việc loại bỏ quy trình thủ công, tự động hóa các bước quan trắc và duy trì nền tảng dữ liệu minh bạch, sẵn sàng cho công tác kiểm tra, giải pháp giúp doanh nghiệp luôn chủ động trước các yêu cầu tuân thủ và kiểm soát rủi ro vận hành.",
        ],
        valuesTitle: "Giá trị mang lại",
        values: [
          { title: "Thúc đẩy mục tiêu ESG & phát triển bền vững", text: "Tạo nền tảng dữ liệu cho mục tiêu phát triển bền vững." },
          { title: "Tối ưu hiệu suất vận hành & tự động hóa quy trình", text: "Tự động hóa kế hoạch và giảm thời gian tổng hợp thủ công." },
          { title: "Minh bạch hóa & dễ dàng truy xuất dữ liệu", text: "Theo dõi nguồn gốc và lịch sử của dữ liệu quan trắc." },
          { title: "Chủ động phòng ngừa & giảm thiểu rủi ro môi trường", text: "Phát hiện dấu hiệu bất thường để xử lý chủ động." },
        ],
        experienceTitle: "CHỦ ĐỘNG KIỂM SOÁT MÔI TRƯỜNG\nTỐI ƯU QUY TRÌNH TUÂN THỦ",
        ctaTitle: "Chủ động kiểm soát môi trường. Tối ưu quy trình tuân thủ.",
        ctaText: "Kết nối kế hoạch quan trắc, kết quả hiện trường và báo cáo quản trị.",
        demo: "Đăng ký demo",
        contact: "Liên hệ tư vấn",
      },
      en: {
        title: "Occupational Hygiene Monitoring",
        eyebrow: "OCCUPATIONAL HYGIENE MONITORING",
        overviewTitle: "Digitize the occupational environment monitoring workflow",
        overview: "Configure monitoring zones, define relevant parameters, schedule sampling and centralize field monitoring data on one connected platform.",
        benefits: ["Replace fragmented manual entry", "Transparent, traceable monitoring data"],
        workflowTitle: "Occupational environment monitoring workflow",
        workflowIntro: "Standardize the process from zone setup and criteria definition to planning and result logging.",
        workflow: ["Area setup & configuration", "Criteria & parameter definition", "Zone metric allocation", "Monitoring plan scheduling", "Data entry & logging"],
        featuresTitle: "Core features",
        features: [
          { title: "Onboarding & compliance support", text: "Set up zones, parameters and thresholds for the organization’s monitoring needs." },
          { title: "Sampling & monitoring schedules", text: "Plan monitoring activities, assign work and track milestones." },
          { title: "Centralized data logging", text: "Enter, store and retrieve monitoring results in one system." },
          { title: "Performance & risk tracking", text: "Aggregate indicators to identify anomalies and act proactively." },
        ],
        detailTitle: "Bridge field operations and management insight",
        detail: [
          "The platform transforms fragmented field measurements into a centralized ecosystem, reducing manual work and preserving a complete monitoring trail.",
          "Transparent, traceable data helps management stay prepared for reviews, identify environmental risk and support wider sustainability goals.",
        ],
        valuesTitle: "Business value",
        values: [
          { title: "ESG enablement", text: "Create a data foundation for sustainable development goals." },
          { title: "Operational efficiency", text: "Automate plans and reduce manual consolidation time." },
          { title: "Transparency & traceability", text: "Follow the origin and history of monitoring data." },
          { title: "Proactive risk mitigation", text: "Identify abnormal indicators for earlier action." },
        ],
        experienceTitle: "PROACTIVE ENVIRONMENTAL CONTROL\nSEAMLESS COMPLIANCE",
        ctaTitle: "Manage environmental data in one system",
        ctaText: "Connect monitoring plans, field results and management reporting.",
        demo: "Book a demo",
        contact: "Contact us",
      },
    },
  },
  safetyCulture: {
    slug: "safety-culture",
    icon: "/assets/module-solutions/safety-culture.png",
    heroImage: "/assets/contractor-management/value-operational-efficiency.png",
    overviewImages: ["/assets/contractor-management/value-operational-efficiency.png", "/assets/risk-management/risk-management-meeting.png", "/assets/contractor-management/value-document-management.png"],
    experienceImages: [
      "/assets/module-solutions/screenshots/safety-culture/campaign-list.png",
      "/assets/module-solutions/screenshots/safety-culture/bradley-curve.png",
      "/assets/module-solutions/screenshots/safety-culture/results-analysis.png",
      "/assets/module-solutions/screenshots/safety-culture/question-detail-rates.png",
    ],
    accent: "#7c3aed",
    accentDark: "#4c1d95",
    copy: {
      vi: {
        title: "Đánh giá văn hóa an toàn",
        eyebrow: "ĐÁNH GIÁ VĂN HÓA AN TOÀN",
        overviewTitle: "Đánh giá văn hóa an toàn",
        overview: "Giải pháp Khảo sát Văn hóa An toàn giúp doanh nghiệp đo lường và nâng tầm nhận thức an toàn lao động dựa trên các tiêu chuẩn quốc tế uy tín. Tích hợp phương pháp luận Đường cong Bradley của DuPont, nền tảng tối ưu hóa toàn bộ quy trình—từ khởi tạo chiến dịch, phát hành khảo sát đa kênh đến tự động tổng hợp kết quả.",
        overviewContinuation: "Bằng việc chuyển hóa phản hồi của nhân viên thành biểu đồ vị trí trên Đường cong Bradley, phần mềm mang đến cho Ban lãnh đạo bức tranh toàn cảnh trực quan về cấp độ văn hóa an toàn hiện tại, làm cơ sở xây dựng lộ trình nâng cấp văn hóa an toàn chủ động và tự giác.",
        benefits: ["Khảo sát ẩn danh, thuận tiện tham gia", "Theo dõi mức độ trưởng thành theo thời gian"],
        workflowTitle: "Quy trình khảo sát văn hóa an toàn",
        workflowIntro: "Từ khởi tạo chiến dịch đến phân tích vị trí văn hóa và xây dựng lộ trình cải thiện.",
        workflow: [
          "Khởi tạo chiến dịch khảo sát",
          "Cấu hình bộ câu hỏi chuẩn hóa theo mô hình Đường cong Bradley của DuPont",
          "Phát hành link/mã QR khảo sát cho nhân viên thực hiện",
          "Tự động phân tích và hiển thị vị trí văn hóa an toàn trên Đường cong Bradley",
        ],
        featuresTitle: "Nhóm tính năng",
        features: [
          { title: "Cơ chế nộp khảo sát ẩn danh", text: "Bảo vệ danh tính người tham gia để khuyến khích phản hồi thẳng thắn." },
          { title: "Ngân hàng câu hỏi chuẩn hóa DuPont Bradley", text: "Sử dụng bộ câu hỏi được cấu hình theo khung đánh giá nhất quán." },
          { title: "Khởi tạo Link & Mã QR khảo sát tức thì", text: "Phát hành khảo sát nhanh đến nhiều nhóm nhân sự và địa điểm." },
          { title: "Trực quan hóa Đường cong Bradley theo thời gian thực", text: "Tổng hợp kết quả và thể hiện vị trí văn hóa trên Đường cong Bradley." },
        ],
        detailTitle: "Biến nhận thức cảm tính thành dữ liệu đo lường",
        detail: [
          "An toàn lao động thực sự không chỉ dừng lại ở sự tuân thủ—đó là kết quả của một văn hóa an toàn thấm nhuần trong từng nhân sự. Giải pháp Khảo sát Văn hóa An toàn biến những nhận thức cảm tính thành dữ liệu đo lường rõ ràng, định hướng doanh nghiệp từng bước tiến xa hơn trên Đường cong Bradley.",
          "Bằng cách nhận diện sớm các khoảng trống nhận thức và theo dõi sự chuyển biến qua từng thời kỳ, ban quản lý hoàn toàn chủ động kiến tạo một môi trường làm việc nơi an toàn trở thành giá trị tự giác của mỗi cá nhân.",
        ],
        valuesTitle: "Giá trị mang lại",
        values: [
          { title: "Nền tảng chuẩn hóa quốc tế", text: "Đo lường nhất quán trên toàn tổ chức." },
          { title: "Khảo sát tiện lợi & Tăng tỷ lệ tham gia", text: "Tiếp cận thuận tiện qua link, QR và cơ chế ẩn danh." },
          { title: "Phân tích tự động cấp độ văn hóa an toàn", text: "Xác định cấp độ trưởng thành văn hóa trực quan." },
          { title: "Lộ trình chuyển đổi dựa trên dữ liệu", text: "Ưu tiên đúng khoảng trống cần cải thiện." },
        ],
        experienceTitle: "ĐO LƯỜNG NHẬN THỨC\nKIẾN TẠO VĂN HÓA AN TOÀN CHỦ ĐỘNG",
        ctaTitle: "Bắt đầu hành trình nâng tầm văn hóa an toàn",
        ctaText: "Lắng nghe nhân sự, đo lường hiện trạng và xác định lộ trình cải thiện phù hợp.",
        demo: "Đăng ký demo",
        contact: "Liên hệ tư vấn",
      },
      en: {
        title: "Safety Culture",
        eyebrow: "SAFETY CULTURE",
        overviewTitle: "Safety Culture",
        overview: "The Safety Culture solution enables organizations to evaluate and elevate their safety mindset through proven global standards. Built upon the renowned DuPont Bradley Curve methodology, the platform streamlines the entire process—from campaign launch and multi-channel survey distribution to real-time response aggregation.",
        overviewContinuation: "By transforming qualitative employee feedback into an objective Bradley Curve mapping, the software provides leadership with a clear visual representation of their current safety stage, empowering targeted strategies toward a proactive, interdependent safety culture.",
        benefits: ["Anonymous, accessible participation", "Maturity tracked over time"],
        workflowTitle: "Safety culture survey workflow",
        workflowIntro: "Move from campaign launch to maturity analysis and a focused improvement roadmap.",
        workflow: ["Campaign Initialization", "Bradley Curve Checklist Mapping", "Multi-Channel Survey Distribution", "Bradley Curve Analytics & Benchmarking"],
        featuresTitle: "Core features",
        features: [
          { title: "100% Anonymized Survey Submission", text: "Protect participant identity and encourage candid feedback." },
          { title: "Pre-configured DuPont Bradley Question Bank", text: "Use a configured question set for consistent assessment." },
          { title: "Instant One-Click Link & QR Generation", text: "Distribute surveys quickly across teams and locations." },
          { title: "Real-Time Bradley Curve Visualization", text: "Aggregate responses and map the organization on the Bradley Curve." },
        ],
        detailTitle: "Turn subjective perception into measurable data",
        detail: [
          "True organizational safety goes beyond compliance—it stems from a deeply ingrained safety culture. The Safety Culture solution turns subjective employee perception into clear, measurable data, guiding your journey along the DuPont Bradley Curve.",
          "By identifying cultural gaps early and tracking progress over time, your management team can cultivate an environment where safety is a shared, proactive value across every operational level.",
        ],
        valuesTitle: "Business value",
        values: [
          { title: "Internationally Recognized Framework", text: "Measure consistently across the organization." },
          { title: "Frictionless Participation & High Response Rates", text: "Make access easy with links, QR codes and anonymity." },
          { title: "Automated Bradley Maturity Mapping", text: "Visualize the current stage of safety culture." },
          { title: "Data-Driven Cultural Roadmap", text: "Prioritize the cultural gaps that matter most." },
        ],
        experienceTitle: "MEASURE PERCEPTION\nBUILD A PROACTIVE SAFETY CULTURE",
        ctaTitle: "Start elevating your safety culture",
        ctaText: "Listen to employees, measure the current state and define a focused improvement roadmap.",
        demo: "Book a demo",
        contact: "Contact us",
      },
    },
  },
  legalCompliance: {
    slug: "legal-compliance",
    icon: "/assets/module-solutions/legal-compliance.png",
    heroImage: "/assets/contractor-management/value-document-management.png",
    overviewImages: [
      "/assets/module-solutions/legal-compliance-overview-v2.png",
      "/assets/module-solutions/legal-value-standardization.png",
      "/assets/module-solutions/legal-value-gap-analysis.png",
      "/assets/module-solutions/legal-value-trend-analysis.png",
    ],
    experienceImages: [
      "/assets/module-solutions/screenshots/legal-compliance/overview-chart.png",
      "/assets/module-solutions/screenshots/legal-compliance/detail-chart.png",
      "/assets/module-solutions/screenshots/legal-compliance/question-list.png",
      "/assets/module-solutions/screenshots/legal-compliance/assessment-period.png",
      "/assets/module-solutions/screenshots/legal-compliance/assessment-screen.png",
    ],
    accent: "#0891b2",
    accentDark: "#155e75",
    copy: {
      vi: {
        title: "Đánh giá tuân thủ pháp luật",
        eyebrow: "LEGAL COMPLIANCE",
        overviewTitle: "Đánh giá tuân thủ pháp luật",
        overview: "Giải pháp đánh giá tuân thủ pháp luật kết hợp hoàn hảo giữa năng lực tư vấn thực địa của chuyên gia và nền tảng số hiện đại, giúp đơn giản hóa toàn bộ quy trình kiểm toán tuân thủ cho nhà máy. Khởi đầu bằng việc khảo sát thực tế, đội ngũ chuyên gia của chúng tôi sẽ cá nhân hóa bộ câu hỏi đánh giá pháp lý bám sát theo đúng quy mô và đặc thù vận hành của doanh nghiệp.",
        overviewContinuation: "Thông qua tài khoản được phân quyền riêng biệt, đội ngũ của bạn dễ dàng thực hiện đánh giá theo từng đợt với hướng dẫn chi tiết cho từng tiêu chí. Hệ thống tự động chuyển hóa dữ liệu đánh giá thành các biểu đồ phân tích trực quan—giúp ban quản lý dễ dàng theo dõi xu hướng tuân thủ qua các đợt kiểm tra, nhận diện sớm rủi ro pháp lý và chủ động sẵn sàng trước mọi kỳ thanh kiểm tra.",
        benefits: ["Bộ tiêu chí bám sát phạm vi vận hành", "Dữ liệu đánh giá trực quan qua từng kỳ"],
        workflowTitle: "Quy trình đánh giá tuân thủ",
        workflowIntro: "Chuẩn hóa từ xác định phạm vi đến đánh giá, phân tích và theo dõi cải thiện.",
        workflow: [
          "Khảo sát thực tế & Cá nhân hóa bộ tiêu chuẩn pháp lý phù hợp",
          "Nhận tài khoản tích hợp sẵn bộ câu hỏi đánh giá đã được chuẩn hóa",
          "Thực hiện đánh giá tuân thủ dễ dàng theo từng câu hỏi/mục tiêu chí",
          "Theo dõi chỉ số tuân thủ qua biểu đồ trực quan và so sánh theo từng đợt",
        ],
        featuresTitle: "Nhóm tính năng",
        features: [
          { title: "Nền tảng pháp lý HSE toàn diện & cập nhật liên tục", text: "Tập trung và cập nhật cơ sở thông tin pháp lý phục vụ hoạt động đánh giá HSE." },
          { title: "Tùy chỉnh bộ câu hỏi tự đánh giá tuân thủ HSE cho doanh nghiệp", text: "Cá nhân hóa bộ câu hỏi theo phạm vi, quy mô và đặc thù vận hành của từng doanh nghiệp." },
          { title: "Quản lý hiệu quả & linh hoạt thích ứng với các thay đổi pháp lý", text: "Hỗ trợ đội ngũ theo dõi yêu cầu mới và chủ động điều chỉnh hoạt động tuân thủ." },
          { title: "Theo dõi hồ sơ/tài liệu tuân thủ dễ dàng & nhanh chóng", text: "Tập trung tài liệu, bằng chứng và lịch sử đánh giá để tra cứu thuận tiện." },
        ],
        detailTitle: "Từ yêu cầu phức tạp đến quy trình minh bạch",
        detail: [
          "Việc đáp ứng các quy định pháp luật phức tạp không nên là rào cản làm cản trở đà phát triển vận hành của doanh nghiệp. Giải pháp đánh giá tuân thủ pháp luật chuyển hóa các yêu cầu pháp lý chằng chịt thành một quy trình số hóa chuẩn hóa, minh bạch và dễ dàng quản lý—kết hợp hoàn hảo giữa góc nhìn chuyên gia thực địa và nền tảng công nghệ trực quan.",
          "Bằng việc đồng nhất tiêu chuẩn đánh giá, minh bạch hóa các điểm thiếu hụt và theo dõi sự tiến bộ qua từng đợt kiểm tra, giải pháp của chúng tôi giúp ban quản lý chủ động nhận diện rủi ro vận hành sớm và tự tin thúc đẩy sự cải tiến liên tục.",
        ],
        valuesTitle: "Giá trị mang lại",
        values: [
          { title: "Cá nhân hóa khung pháp lý & Tập trung đúng phạm vi", text: "Bám sát quy mô và đặc thù vận hành của doanh nghiệp." },
          { title: "Chuẩn hóa quy trình & Đồng nhất kết quả đánh giá", text: "Thống nhất cách thực hiện, ghi nhận và so sánh kết quả." },
          { title: "Báo cáo biểu đồ trực quan & Phát hiện ngay điểm thiếu hụt", text: "Giúp ban quản lý nhanh chóng nhận diện khoảng trống tuân thủ." },
          { title: "Theo dõi xu hướng & So sánh hiệu quả qua các đợt", text: "Theo dõi sự tiến bộ và hiệu quả cải thiện theo thời gian." },
        ],
        experienceTitle: "TUÂN THỦ MINH BẠCH\nCẢI TIẾN CHỦ ĐỘNG",
        ctaTitle: "Sẵn sàng hơn cho mỗi kỳ đánh giá",
        ctaText: "Quản lý tiêu chí, bằng chứng và kết quả tuân thủ trên một nền tảng thống nhất.",
        demo: "Đăng ký demo",
        contact: "Liên hệ tư vấn",
      },
      en: {
        title: "Legal Compliance",
        eyebrow: "LEGAL COMPLIANCE",
        overviewTitle: "Legal Compliance",
        overview: "The Legal Compliance solution bridges on-site regulatory expertise with an intuitive digital platform to simplify complex factory compliance audits. Starting with a thorough site survey, our experts tailor specialized legal questionnaires directly to your facility's operational scope.",
        overviewContinuation: "Through a dedicated portal, your team can seamlessly execute step-by-step evaluations with clear guidance at every check. The platform automatically aggregates raw audit data into dynamic visual dashboards, allowing management to track trends, pinpoint regulatory risks and stay ready for official inspections.",
        benefits: ["Criteria aligned to operational scope", "Visual results across assessment periods"],
        workflowTitle: "Compliance assessment workflow",
        workflowIntro: "Standardize the journey from scoping through assessment, analysis and continuous improvement.",
        workflow: [
          "On-Site Assessment & Scope Tailoring",
          "Smart Account & Checklist Provisioning",
          "Streamlined Compliance Audit",
          "Visual Dashboard & Trend Analytics",
        ],
        featuresTitle: "Core features",
        features: [
          { title: "Comprehensive & updated Legal HSE platform", text: "Centralize and update legal information that supports HSE assessments." },
          { title: "Customize the questionnaire for company HSE self-assessment", text: "Tailor criteria to the organization's scope, scale and operating context." },
          { title: "Efficiently manage and adapt to regulatory changes", text: "Help teams monitor new requirements and adjust compliance activity proactively." },
          { title: "Easy & quick tracking compliance documents", text: "Centralize evidence, documents and assessment history for quick retrieval." },
        ],
        detailTitle: "Turn complexity into a transparent workflow",
        detail: [
          "Navigating complex environmental, health and safety regulations should never slow down operational momentum. The solution transforms intricate legal requirements into a structured, transparent and manageable workflow that combines expert on-site insights with intuitive digital execution.",
          "By standardizing evaluation criteria, visualizing compliance gaps and tracking progress across audit cycles, the platform enables management to mitigate operational risks early and drive continuous improvement with confidence.",
        ],
        valuesTitle: "Business value",
        values: [
          { title: "Tailored Legal Framework & Focused Scope", text: "Focus assessment on the relevant operational scope." },
          { title: "Standardized Audit Process & Consistent Evaluation", text: "Apply consistent evaluation and record keeping." },
          { title: "Dynamic Visual Dashboards & Instant Gap Analysis", text: "See missing controls through visual reporting." },
          { title: "Longitudinal Tracking & Benchmark Comparison", text: "Compare improvement across assessment cycles." },
        ],
        experienceTitle: "TRANSPARENT COMPLIANCE\nPROACTIVE IMPROVEMENT",
        ctaTitle: "Be ready for every assessment",
        ctaText: "Manage criteria, evidence and compliance results on one connected platform.",
        demo: "Book a demo",
        contact: "Contact us",
      },
    },
  },
  chemicalManagement: {
    slug: "chemical-management",
    icon: "/assets/module-solutions/chemical-management.png",
    heroImage: "/assets/contractor-management/value-risk-management.png",
    overviewImages: ["/assets/contractor-management/value-risk-management.png", "/assets/module-solutions/equipment-hero.jpg", "/assets/csms/core-workplace.jpg"],
    accent: "#dc2626",
    accentDark: "#7f1d1d",
    copy: {
      vi: {
        title: "Quản lý hóa chất & phóng xạ",
        eyebrow: "CHEMICAL & RADIATION MANAGEMENT",
        overviewTitle: "Kiểm soát tập trung các tác nhân nguy hại",
        overview: "Giải pháp hỗ trợ doanh nghiệp lập danh mục hóa chất và nguồn phóng xạ, quản lý hồ sơ an toàn, theo dõi vị trí lưu trữ, hạn sử dụng, hoạt động cấp phát và các đầu việc kiểm soát liên quan.",
        benefits: ["Thông tin nguy hại tập trung, dễ truy xuất", "Theo dõi tồn kho và lịch sử sử dụng"],
        workflowTitle: "Quy trình quản lý hóa chất & phóng xạ",
        workflowIntro: "Một quy trình số hóa từ khai báo danh mục đến theo dõi sử dụng, kiểm kê và báo cáo.",
        workflow: ["Khai báo danh mục và phân loại nguy hại", "Gắn hồ sơ SDS, giấy phép và tài liệu", "Quản lý kho, vị trí và số lượng", "Cấp phát, sử dụng và thu hồi", "Kiểm kê, cảnh báo và báo cáo"],
        featuresTitle: "Nhóm tính năng",
        features: [
          { title: "Danh mục & hồ sơ an toàn", text: "Tập trung thông tin nhận diện, phân loại và tài liệu an toàn gắn với từng tác nhân." },
          { title: "Quản lý kho & vị trí", text: "Theo dõi số lượng, đơn vị quản lý, khu vực lưu trữ và biến động tồn kho." },
          { title: "Cảnh báo theo mốc", text: "Nhắc hạn sử dụng, kỳ kiểm tra và các mốc giấy phép do doanh nghiệp cấu hình." },
          { title: "Lịch sử & báo cáo", text: "Lưu vết nhập, cấp phát, sử dụng, thu hồi và tổng hợp dữ liệu quản trị." },
        ],
        detailTitle: "Dữ liệu nhất quán cho hoạt động kiểm soát nguy hại",
        detail: [
          "Việc tập trung danh mục, hồ sơ an toàn và vị trí lưu trữ giúp người phụ trách nhanh chóng biết doanh nghiệp đang quản lý tác nhân nào, ở đâu và thuộc đơn vị nào.",
          "Lịch sử biến động và cảnh báo theo mốc hỗ trợ kiểm kê, chuẩn bị hồ sơ và xử lý kịp thời các công việc nội bộ. Các yêu cầu pháp lý cụ thể vẫn cần được doanh nghiệp cấu hình và xác nhận theo phạm vi áp dụng thực tế.",
        ],
        valuesTitle: "Giá trị mang lại",
        values: [
          { title: "Kiểm soát tập trung", text: "Một nguồn dữ liệu cho hóa chất, nguồn phóng xạ và hồ sơ liên quan." },
          { title: "Truy xuất nhanh", text: "Tìm đúng SDS, vị trí và lịch sử khi cần." },
          { title: "Chủ động cảnh báo", text: "Theo dõi các mốc nội bộ quan trọng, hạn chế bỏ sót." },
          { title: "Minh bạch sử dụng", text: "Ghi nhận nhập, xuất, cấp phát và tồn kho theo thời gian." },
        ],
        experienceTitle: "QUẢN LÝ TẬP TRUNG\nTRUY XUẤT NHANH\nKIỂM SOÁT CHỦ ĐỘNG",
        ctaTitle: "Số hóa hoạt động quản lý tác nhân nguy hại",
        ctaText: "Tập trung hồ sơ, vị trí, tồn kho và lịch sử sử dụng trong một quy trình rõ ràng.",
        demo: "Đăng ký demo",
        contact: "Liên hệ tư vấn",
      },
      en: {
        title: "Chemical & Radiation Management",
        eyebrow: "CHEMICAL & RADIATION MANAGEMENT",
        overviewTitle: "Centralize control of hazardous agents",
        overview: "Maintain chemical and radiation-source registers, safety records, storage locations, expiry dates, issuance history and related control activities in one system.",
        benefits: ["Hazard information centralized and accessible", "Inventory and usage history tracked"],
        workflowTitle: "Chemical & radiation workflow",
        workflowIntro: "Digitize the journey from registration and classification to use, inventory and reporting.",
        workflow: ["Register and classify hazardous agents", "Attach SDS, licenses and records", "Manage storage locations and quantities", "Issue, use and return materials", "Inventory, alerts and reporting"],
        featuresTitle: "Core features",
        features: [
          { title: "Register & safety records", text: "Centralize identification, classification and safety documents for each agent." },
          { title: "Inventory & location management", text: "Track quantity, ownership, storage areas and stock movement." },
          { title: "Milestone alerts", text: "Monitor expiry, inspection and configured permit milestones." },
          { title: "History & reporting", text: "Record receipts, issuance, use and return activity for management reporting." },
        ],
        detailTitle: "Consistent data for hazardous-agent control",
        detail: [
          "Centralized registers, safety records and storage locations help responsible teams understand which agents are managed, where they are held and who owns each record.",
          "Movement history and configurable alerts support inventory checks, record preparation and timely internal action. Specific legal obligations should still be configured and verified for the organization’s actual scope.",
        ],
        valuesTitle: "Business value",
        values: [
          { title: "Centralized control", text: "One source for chemicals, radiation sources and related records." },
          { title: "Fast retrieval", text: "Find the right SDS, location and history when needed." },
          { title: "Proactive alerts", text: "Track key internal milestones and reduce missed actions." },
          { title: "Transparent usage", text: "Record receipts, issuance and stock movement over time." },
        ],
        experienceTitle: "CENTRALIZE RECORDS\nRETRIEVE FAST\nCONTROL PROACTIVELY",
        ctaTitle: "Digitize hazardous-agent management",
        ctaText: "Bring records, locations, inventory and usage history into one clear workflow.",
        demo: "Book a demo",
        contact: "Contact us",
      },
    },
  },
} as const satisfies Record<string, ModulePageConfig>;
